version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: QPyErTwcxv7IGlN+tHKTlShFS7+C/m1kb5NbhHYIv3yf+wmIRUELEK8xJtPyeHna

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

artifacts:
  - path: dist\**\*.nupkg
  - path: dist\**\*Setup*.exe

test: off